Tesing

diff --git a/bitbucket-pipelines.yml b/bitbucket-pipelines.yml
--- a/bitbucket-pipelines.yml
+++ b/bitbucket-pipelines.yml
@@ -1,7 +1,7 @@
-#  Template maven-build
+# Template maven-build
 
-#  This template allows you to test and build your Java project with Maven.
-#  The workflow allows running tests, code checkstyle and security scans on the default branch.
+# This template allows you to test and build your Java project with Maven.
+# The workflow allows running tests, code checkstyle and security scans on the default branch.
 
 # Prerequisites: pom.xml and appropriate project structure should exist in the repository.
 
@@ -10,18 +10,17 @@ image: maven:3.9.2
 pipelines:
   default:
     - parallel:
-      - step:
-          name: Build and Test
-          caches:
-            - maven
-          script:
-            - mvn clean install --file Automation_Scripts/pom.xml || echo "Build failed"
-          after-script:
+        - step:
+            name: Build and Test
+            caches:
+              - maven
+            script:
+              - mvn clean install --file Automation_Scripts/pom.xml || echo "Build failed"
+            after-script:
               # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
-            - pipe: atlassian/checkstyle-report:0.3.0
+              - pipe: atlassian/checkstyle-report:0.3.0
 
- # Add a new step to handle failures and create a Jira issue
-             - step:
+        - step:
             name: Create Jira Issue on Failure
             script:
               - >
@@ -41,9 +40,10 @@ pipelines:
                         Test results: $test_results
                   fi
                 fi
-      - step:
-          name: Security Scan
-          script:
-            # Run a security scan for sensitive data.
-            # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
-            - pipe: atlassian/git-secrets-scan:0.5.1
+
+        - step:
+            name: Security Scan
+            script:
+              # Run a security scan for sensitive data.
+              # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
+              - pipe: atlassian/git-secrets-scan:0.5.1
