test

diff --git a/bitbucket-pipelines.yml b/bitbucket-pipelines.yml
--- a/bitbucket-pipelines.yml
+++ b/bitbucket-pipelines.yml
@@ -9,18 +9,30 @@ pipelines:
         script:
           - mvn clean test --file Automation_Scripts/pom.xml
         after-script:
-          - if [[ $BITBUCKET_EXIT_CODE -ne 0 ]]; then
-              echo "Step failed";
-              pipe: atlassian/jira-create-issue:0.7.0
-              variables:
-                JIRA_BASE_URL: $JIRA_BASE_URL
-                JIRA_USER_EMAIL: $JIRA_USER_EMAIL
-                JIRA_API_TOKEN: $JIRA_API_TOKEN
-                JIRA_PROJECT: $JIRA_PROJECT
-                JIRA_ISSUE_TYPE: "Bug"
-                JIRA_ISSUE_SUMMARY: "Build Failure: $(date +'%Y-%m-%d %H:%M:%S')"
-                JIRA_ISSUE_DESCRIPTION: "This issue is created from Bitbucket Pipelines.";
-            fi
+         
+          - pipe: atlassian/checkstyle-report:0.3.0
+        
+
+    # This step tries to create a Jira issue only if the build fails
+    - step:
+        name: Create Jira Issue on Build Failure
+        script:
+          - >
+            mvn clean test --file Automation_Scripts/pom.xml
+            || {
+                 echo "Build and test failed";
+                 pipe: atlassian/jira-create-issue:0.7.0
+                 variables:
+                   JIRA_BASE_URL: $JIRA_BASE_URL
+                   JIRA_USER_EMAIL: $JIRA_USER_EMAIL
+                   JIRA_API_TOKEN: $JIRA_API_TOKEN
+                   JIRA_PROJECT: $JIRA_PROJECT
+                   JIRA_ISSUE_TYPE: "Bug"
+                   JIRA_ISSUE_SUMMARY: "Build Failure Detected: $(date +'%Y-%m-%d %H:%M:%S')"
+                   JIRA_ISSUE_DESCRIPTION: "A build failure occurred in Bitbucket Pipelines."
+                 exit 1;
+               }
+       
 
     - step:
         name: Security Scan
